### ISSUE TITLE
Does advanced flow control only exist in tofino2 architecture?

### ISSUE THREAD

**Issue by Yahoo-90** [conweave-project/conweave-p4#1]
Hello, I checked the contents of the _tofino.p4_ and _tofino2.p4_ files and found that there is no _adv_flow_control_ field in the _ingress_intrinsic_metadata_for_deparser_t_ section in the tofino architecture, while the tofino2 architecture contains this field. Does this mean that the advanced flow control function can only be used in **tofino2**?

**Comment by ChahwanSong** [comment]
Hi @Yahoo-90,

Yes, correct. Advanced flow control (e.g., queue pause/resume capability) is supported only on Tofino2 architecture. Tofino1 does not have such a feature. 

Alternatively, you may want to use "packet recirculation" to implement what you want. But, you need to be careful as it can easily cause queue overflow and subsequent packet drops if the queue's packet flush speed is slower than the packet influx speed to the queue.
