### ISSUE TITLE
A question about queue pause.

### ISSUE THREAD

**Issue by skyWalkerZJ** [conweave-project/conweave-p4#2]
the 309th line of code in native_afc.p4：
if (meta.where_to_afc == 0) { /* AFC at Ingress */
                    /* pass adv_flow_ctl message */
                    ig_intr_md_for_dprsr.adv_flow_ctl = hdr.afc_msg.adv_flow_ctl;
                    ig_intr_md_for_tm.bypass_egress = meta.eg_bypass; // uncomment to bypass egress processing
                    do_check_afc_record(); // debugging
}
Question: Does the metadata ig_intr_md_for_dprsr contain a parameter named adv_flow_ctl? What does this line of code mean? Why does it achieve the effect of queue pause?

thanks :)

**Comment by ChahwanSong** [comment]
Hi @skyWalkerZJ ,

On Tofino2 architecture, the ingress/egress intrinsic metadata field includes the field `adv_flow_ctl`. 
In the pipeline, a user can update the field to pause/resume queues or more advanced features (e.g., credit-based). 
Then, at the deparser of each pipeline, the field is read and activated. 

The line of code means nothing but to copy the pre-coded field at the packet's header to the intrinsic metadata field `adv_flow_ctl`. Hope this helps your understanding.

**Comment by skyWalkerZJ** [comment]
Thank you for your prompt response👍 . I have consulted the documentation for Tofino2 and found the solution. The issue can be closed now.
